// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebwhrqydzowwsgzcqsua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVid2hycXlkem93d3NnemNxc3VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTU1ODgsImV4cCI6MjA3MDkzMTU4OH0.IFR2p6WohKsHgGe9sBF3js55MBrnixAsTzAS4S_p-sA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});